version: '3.9'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    environment:
      - DB_HOST=mariadb
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge
